### ISSUE TITLE
Service Layer (Persistance Layer)

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/Open-Grants-Program#38]
Add the possibility to add a light weight database. Implement service layer extension to use a light weight database as a persistence layer.

**Comment by darkfriend77** [comment]
The possibility of how we can persist doesn't need to be a database, can also be file storage instead of the current in-memory solution.

**Comment by darkfriend77** [comment]
Implementation of an additional delegate to be used for any persistence layer, database, file, whatever makes sense.

https://github.com/ajuna-network/Ajuna.SDK/tree/add-ersistence-layer
https://github.com/ajuna-network/Ajuna.SDK/pull/18 (pull request in review)

**Comment by dimitrispaxinos** [comment]
# Testing Guide 

## Prerequisites 

- A running Substrate Node: [monthly-2022-07](https://github.com/paritytech/substrate/releases/tag/monthly-2022-07) in `--dev` mode.
- [Ajuna.Net Template](https://github.com/ajuna-network/Ajuna.SDK) is installed in order to scaffold the projects/toolchain.


## Get everything up and running 

The projects have to be scaffolded first:

So we create a new directory:

```sh
mkdir persistence-test
cd persistence-test 
```

We run the respective dotnet ajuna commands:

```sh
dotnet new sln
dotnet new ajuna \
   --sdk_version 0.1.16 \
   --rest_service AjunaExample.RestService \
   --net_api AjunaExample.NetApi \
   --rest_client AjunaExample.RestClient \
   --metadata_websocket ws://127.0.0.1:9944 \
   --force \
   --allow-scripts yes
```

We then open the newly created solution with the IDE of our choice. 

We now go to the `Startup.cs `class of the `AjunaExample.RestService` project and activate the persistence layer by setting the `_useLocalStoragePersistence` variable to `true`. It's in line 58.

```csharp
// Set to true to activate persistence 
 private readonly bool _useLocalStoragePersistence = true;
```

Then we go back to the command line in the `persistence-test` folder and start the `AjunaExample.RestService`:

```sh
cd AjunaExample.RestService
dotnet run 
```

We will then see that a new CSV file is created within the `AjunaExample.RestService` folder with the following format: `Storage_Changes_20220721_####.csv`.

This file contains all change details including the identifier, change action and new value

![image](https://user-images.githubusercontent.com/4278331/180243175-a8ccfd64-c5df-4eda-94b2-2a0509cd3bf2.png)
