### ISSUE TITLE
Unity - Tutorial Video "Adding a custom pallet and accessing it in unity"

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/Open-Grants-Program#53]
Tutorial video on adding a custom pallet and accessing it in unity

**Comment by dimitrispaxinos** [comment]
Please be sure to first go through issue #52 since this issue builds on top of it.


## Process Description 
What we do here is modify the original implementation described in issue #52:

### Add a new pallet 

We will switch to `substrate node template` node now that contains the 'new' _template_ pallet with the `Something` storage and the `DoSomething` extrinsic. 

### Regenerate the necessary projects  

We will then regenerate the .NET projects and DLLs we will use in our Unity app

### Modify SubstrateNET.BasicUnityDemo

We will modify the Unity app to poll for the `Something` Storage changes and execute the `DoSomething` Extrinsic to set Something's value. 

## Video Tutorial

The above-described process is covered in this [video](https://www.loom.com/share/630e4f49c21c4f438576b492298d90b8). 

## Running the app

If you want to try out the modified app, you can find the installation instructions in the [SubstrateNET.BasicUnityDemo](https://github.com/ajuna-network/SubstrateNET.BasicUnityDemo)'s README file. Please keep in mind that for this issue, you will need to work on the `substrate-node-template` branch.
